CREATE DATABASE IF NOT EXISTS guest;

USE guest;

DROP TABLE IF EXISTS SERIES, ACTOR, GENRE, SEASON, CAST, SERIES_GENRE, ACTOR_SZN;  
CREATE TABLE SERIES
(
	SeriesId	INT PRIMARY KEY AUTO_INCREMENT,
	Title		VARCHAR(128) UNIQUE NOT NULL,
    Rate        DECIMAL NOT NULL,  
	Premiere		INT NOT NULL,
	Finale		INT DEFAULT NULL,
    RuntimeEpisode  INT NOT NULL,
    Overview   		 LONGTEXT NOT NULL
);

CREATE TABLE ACTOR
(
	ActorId	    INT PRIMARY KEY AUTO_INCREMENT,
	Name 		VARCHAR(128) NOT NULL
);

CREATE TABLE GENRE
(
	GenreId 	INT PRIMARY KEY AUTO_INCREMENT,
	Label		VARCHAR(128) NOT NULL
);

CREATE TABLE SEASON
(
	SeasonId 	INT PRIMARY KEY AUTO_INCREMENT,
	SeriesId	INT NOT NULL,
	FOREIGN KEY(SeriesId) REFERENCES SERIES(SeriesId)
);

CREATE TABLE CAST
(
	SeriesId INT NOT NULL,
	ActorId INT NOT NULL,
	PRIMARY KEY(SeriesId, ActorId),
	FOREIGN KEY(SeriesId) REFERENCES SERIES(SeriesId),
	FOREIGN KEY(ActorId) REFERENCES ACTOR(ActorId)
);

CREATE TABLE SERIES_GENRE
(
	SeriesId INT NOT NULL,
	GenreId INT NOT NULL,
	PRIMARY KEY(SeriesId, GenreId),
	FOREIGN KEY(SeriesId) REFERENCES SERIES(SeriesId),
	FOREIGN KEY(GenreId) REFERENCES GENRE(GenreId)
);
